import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Toaster} from '@/components/ui/sonner'
import {Header} from '@/components/header'
import {Footer} from '@/components/footer'
import {TooltipProvider} from '@/components/ui/tooltip'

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen h-screen max-h-screen bg-background relative`}>
        <Header/>
        <TooltipProvider>
            {children}
        </TooltipProvider>
        <Footer/>
        <Toaster/>
        </body>
        </html>
    );
}
